server:
  port: 8092
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: theClient
      clientSecret: thisissecret
    resource:
      userInfoUri: http://localhost:8080/user